### Listar atendentes
GET https://localhost:7288/api/atendente/listar

### Buscar atendente por nome
GET https://localhost:7288/api/atendente/buscar/Elis

### Cadastrar atendente
POST https://localhost:7288/api/atendente/cadastrar
Content-Type: application/json

{
    "nome" : "Emanuel"
}


# {
#     "nome" : "Elis"
# }


### Remover atendente pelo ID
DELETE https://localhost:7288/api/atendente/deletar/1

### ALTERAR atendente pelo ID
PUT https://localhost:7288/api/atendente/alterar/2
Content-Type: application/json

{
    "nome" : "Francisco"
}