### Listar cardapio
GET https://localhost:7288/api/cardapio/listar

### Buscar cardapio por sabor
GET https://localhost:7288/api/cardapio/buscar/calabresa

### Cadastrar cardapio
POST https://localhost:7288/api/cardapio/cadastrar
Content-Type: application/json

{
    "sabor" : "milho",
    "preco" : 30,
    "descricao" : "molho de tomate queijo e milho"
    

}



### Remover cardapio pelo ID
DELETE https://localhost:7288/api/cardapio/deletar/1

### Alterar cardapio pelo ID
PUT https://localhost:7288/api/cardapio/alterar/2
Content-Type: application/json

{
   "sabor" : "frango",
    "descricao" : "molho de tomate queijo e frango",
    "preco" : 30

}

