### Listar cardapio
GET https://localhost:7288/api/cardapio/listar

### Buscar cardapio por sabor
GET https://localhost:7288/api/cardapio/buscar/1

### Cadastrar cardapio
POST https://localhost:7288/api/cardapio/cadastrar
Content-Type: application/json

# {
#     "sabor" : "Calabresa",
#     "descricao" : "Massa tradicional, molho de tomate, queijo, calabresa e orégano",
#     "preco" : 20
# }

{
    "sabor" : "Margherita",
    "descricao" : "massa tradicional, molho de tomate, queijo mozzarella, manjericão fresco e um fio de azeite de oliva",
    "preco" : 30
}

# {
#     "sabor" : "Frango com Catupiry",
#     "descricao" : "massa tradicional, molho de tomate, frango desfiado, requeijão Catupiry e queijo",
#     "preco" : 50
# }

# {
#     "sabor" : "Quatro Queijos",
#     "descricao" : "massa tradicional, molho de tomate, mozzarella, gorgonzola, parmesão e provolone",
#     "preco" : 60
# }

# {
#     "sabor" : "Portuguesa",
#     "descricao" : "massa tradicional, molho de tomate, queijo mozzarella, presunto, ovos cozidos, cebola, azeitonas e pimentão",
#     "preco" : 40
# }

### Remover cardapio pelo ID
DELETE https://localhost:7288/api/cardapio/deletar/2

### Alterar cardapio pelo ID
PUT https://localhost:7288/api/cardapio/alterar/4
Content-Type: application/json

{
    "sabor" : "Margherita",
    "descricao" : "massa tradicional, molho de tomate, queijo mozzarella, manjericão fresco e um fio de azeite de oliva",
    "preco" : 35
}