### Listar cliente
GET https://localhost:7288/api/cliente/listar

### Buscar cliente por nome
GET https://localhost:7288/api/cliente/buscar/Bruna

### Cadastrar cliente
POST https://localhost:7288/api/cliente/cadastrar
Content-Type: application/json

# {
#     "nome" : "Larissa",
#     "endereco" : "Rua dos morangos",
#     "telefone" : 997465958

# }

{
    "nome" : "Bruna",
    "endereco" : "Rua das Rosas",
    "telefone" : 998754569

}

# {
#     "nome" : "Carlos",
#     "endereco" : "Rua das Laranjeiras",
#     "telefone" : 997465987
# }

### Remover cliente pelo ID
DELETE https://localhost:7288/api/cliente/deletar/6

### Alterar cliente pelo ID
PUT https://localhost:7288/api/cliente/alterar/2 
Content-Type: application/json

# {
#     "nome" : "Bruna",
#     "endereco" : "Rua das Rosas",
#     "telefone" : 998754569

# }

{
    "nome" : "Larissa",
    "endereco" : "Rua dos Morangos",
    "telefone" : 997465958

}

