### LISTAR pedidos
GET https://localhost:7288/api/pedido/listar

### CADASTRAR pedidos
POST https://localhost:7288/api/pedido/cadastrar
Content-Type: application/json

{
    "AtendenteId" : "2",
    "ClienteId" : "2",
    "CardapioId" : 1,
    "TotalPedido" : 1
}