### LISTAR pedidos
GET https://localhost:7288/api/pedido/listar

### Buscar pedido por Cliente
GET https://localhost:7288/api/pedido/listarPorCliente/Larissa

### CADASTRAR pedidos
POST https://localhost:7288/api/pedido/cadastrar
Content-Type: application/json

{
    "atendenteId" : 1,
    "carrinhoId" : 2
}

### DELETAR pedido
DELETE https://localhost:7288/api/pedido/deletar/2